// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuNepkWISQF9ajQEFkawing35tgIRx19s',
    appId: '1:798560423525:web:47b2110b1c0616f067c08c',
    messagingSenderId: '798560423525',
    projectId: 'cs-project-ba291',
    authDomain: 'cs-project-ba291.firebaseapp.com',
    storageBucket: 'cs-project-ba291.firebasestorage.app',
    measurementId: 'G-ZV8PM7GDQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7_Bn0HM12qfSpAdBsskAm2QLNQXefCJQ',
    appId: '1:798560423525:android:ca76a3f2b635eeba67c08c',
    messagingSenderId: '798560423525',
    projectId: 'cs-project-ba291',
    storageBucket: 'cs-project-ba291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvz4CE5XMYo0UXTq8Ag-2238pKJqfbkyw',
    appId: '1:798560423525:ios:2fe6ca22ea17e6ba67c08c',
    messagingSenderId: '798560423525',
    projectId: 'cs-project-ba291',
    storageBucket: 'cs-project-ba291.firebasestorage.app',
    iosBundleId: 'com.example.mindcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvz4CE5XMYo0UXTq8Ag-2238pKJqfbkyw',
    appId: '1:798560423525:ios:2fe6ca22ea17e6ba67c08c',
    messagingSenderId: '798560423525',
    projectId: 'cs-project-ba291',
    storageBucket: 'cs-project-ba291.firebasestorage.app',
    iosBundleId: 'com.example.mindcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuNepkWISQF9ajQEFkawing35tgIRx19s',
    appId: '1:798560423525:web:fcf1c75de7c83c0567c08c',
    messagingSenderId: '798560423525',
    projectId: 'cs-project-ba291',
    authDomain: 'cs-project-ba291.firebaseapp.com',
    storageBucket: 'cs-project-ba291.firebasestorage.app',
    measurementId: 'G-2XQTWK5TWD',
  );

}